version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: 'board_postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-board}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  web:
    build: .
    restart: unless-stopped
    container_name: 'board_django'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-board}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - board:/app
    depends_on:
      - postgres

volumes:
  board:
  postgres:
