# Generated by Django 4.1.7 on 2023-04-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('accept', 'Can accept a comment')], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
